### ISSUE TITLE
Caps on previous iSights saved at double CCD sensor resolution

### ISSUE THREAD

**Issue by rcbarnes** [rharder/imagesnap#1]
I poked around in the code very briefly and it may be a consequence of the camera returning digitally interpolated data, but the color performance is so noisy the quadrupled pixel count is especially wasteful.  Is there an easy way to downconvert the image before returning it?

**Comment by rharder** [comment]
Circling back to an old comment: I'm not aware of how to do this. I'm really just letting the built-in Apple functions handle the image capture.
