### ISSUE TITLE
Repeated image capture mode leaks memory equal to total size of images saved

### ISSUE THREAD

**Issue by rcbarnes** [rharder/imagesnap#2]

**Comment by doersino** [comment]
+1

**Comment by doersino** [comment]
I've written a bash wrapper that works around this issue: https://gist.github.com/doersino/fdca8e065eb30e030ef2

**Comment by Noreaster76** [comment]
@rcbarnes @doersino https://github.com/rharder/imagesnap/pull/12

**Comment by Noreaster76** [comment]
I could be wrong, but I am pretty sure https://github.com/rharder/imagesnap/pull/13 resolves this memory leak. I ran https://github.com/rharder/imagesnap/pull/13 in Profiler's Leaks tool and I don't see the same continually increasing memory usage.

**Comment by duality72** [comment]
+1
