### ISSUE TITLE
problem whit imagesnap -t

### ISSUE THREAD

**Issue by toshibochan** [rharder/imagesnap#23]
I have a problem with using -t. 
this is my code: "imagesnap -w 2 ~/Desktop/$(date +%y%m%d%H%M%S).jpg" this is work good and photo is saved in desktop with "180331141210.jpg" 
but if use "imagesnap -w 2 -t 10 ~/Desktop/$(date +%y%m%d%H%M%S).jpg" the file only save in user folder with name "snapshot-00000-2018-03-31_14-11-27.933.jpg".
please help

**Comment by wkoffel** [comment]
I encountered this also, it appears that the new timelapse feature hardcodes the file name.

https://github.com/rharder/imagesnap/blob/a39b0bde4c3ed087d8cce8b83589cdf6b12a3471/ImageSnap.m#L128

For me, I just wanted it to overwrite the current image every x.xx seconds. Your use-case (a custom sequenced filename) is trickier.

Either solution would require a small source patch.

**Comment by umutbalkan** [comment]
@wkoffel you can simply call imagesnap in a loop and use the -w flag as a timer

**Comment by rharder** [comment]
Recommend umutbalkan's solution.
