### ISSUE TITLE
Please rebuild imagesnap executable

### ISSUE THREAD

**Issue by LeviSchuck** [rharder/imagesnap#25]
Per Pull request #17 the binary here is out of date, so `brew` or direct download from GitHub is not usable on high sierra. 

I've got it built locally and working, but it'd be better if a trusted user actually pushed the binary to this repo :)

**Comment by JayBrown** [comment]
Second that: would like to install it via `brew` too. Version 0.2.7 then?

PS: you can still get a working v0.2.5 from sourceforge or as part of other software like VUWER.

**Comment by rharder** [comment]
So I tried running the binary just now (July 2019) with Mojave 10.14.5.  Binary works fine.  I tried rebuilding it with xcodebuild: byte-for-byte identical build.  

Not familiar with how to put it in brew.

**Comment by rharder** [comment]
I'm not familiar with getting something submitted to brew, but maybe it's time to look into that.
