### ISSUE TITLE
0.2.6 not mentioned in read me, source, or old web sites; disconnect between SourceForge and GitHub

### ISSUE THREAD

**Issue by ryandesign** [rharder/imagesnap#29]
Version 0.2.6 was tagged in 2017, but ImageSnap.m still says the version is 0.2.5, and version 0.2.6 isn't mentioned in the changelog section of README.md or ReadMeOrDont.rtf. The [project's web site](http://iharder.net/imagesnap) and the [project's SourceForge page](https://sourceforge.net/projects/iharder/files/imagesnap/) also still say 0.2.5 is the latest version. The web site and the SourceForge page make no mention of the fact that the project has moved to GitHub.

**Comment by rharder** [comment]
Starting to bring all these up to date now.
