### ISSUE TITLE
Filename and newline no longer printed after taking snapshot

### ISSUE THREAD

**Issue by ryandesign** [rharder/imagesnap#30]
The readme shows that when taking a snapshot, the filename is printed, presumably followed by a newline:

```
$ imagesnap
Capturing image from device "iSight"..................snapshot.jpg
```

With 0.2.6, this no longer happens:

```
$ imagesnap
Capturing image from device "<AVCaptureDALDevice: 0x7fad05719cc0 [FaceTime HD Camera][0x1420000005ac8600]>"...$
```

Note even the lack of newline at the end of the line before my command prompt is printed again.

Looks like this regression crept in when the code was restructured as a companion to QTKit being replaced by AVFoundation in #13.

**Comment by rharder** [comment]
Fixed in upcoming v0.2.10 release
