### ISSUE TITLE
check on the latest release

### ISSUE THREAD

**Issue by chenrui333** [rharder/imagesnap#33]
👋  it looks like the latest release 0.2.8 did not get marked as `latest release`, just raising an issue to call that out. Thanks.

relates to https://github.com/Homebrew/homebrew-core/pull/72486

**Comment by chenrui333** [comment]
cc @rharder

**Comment by rharder** [comment]
Thanks for that.  I've got some more tweaks/releases coming out, so I'll try to fix that.
