### ISSUE TITLE
Images extremely dark on new Mac Air Mid 2013s A1466

### ISSUE THREAD

**Issue by jacobrosenthal** [rharder/imagesnap#4]
Camera works fine in photobooth, but command line shots that are dark. If theres tons of light they sort of come out, but are still very dark. I'm guessing some sort of iso setting is now available and needs to be set during capture?

Macosx 10.8 Build 12E3067

![imagesnap](https://f.cloud.github.com/assets/455796/972996/8ffb8cb2-0613-11e3-8350-11fcc620b430.jpg)

![Photobooth](https://f.cloud.github.com/assets/455796/972998/aaa3d01a-0613-11e3-900f-7271f695eef1.jpg)

**Comment by memming** [comment]
I am experiencing the same problem. -w 2 does fix it.
Mac Book Pro Mid 2014 with the FaceTime HD Camera.
Mac OS X 10.10.1 (Yosemite)

**Comment by SlightlyCyborg** [comment]
Thankyou so much for this!! I was having the same problem

**Comment by Alhadis** [comment]
Happening here too... Mavericks, `brew install`ed, total blackness... odd thing is, when I clamped the luminosity in Photoshop, I noticed white specks appearing on what should've been *NOTHING*.

<img src="https://cloud.githubusercontent.com/assets/2346707/16156487/d976b7d4-34f7-11e6-9b8c-77b80e579c83.png" width="600" />

What was *actually* going on in the picture:

<img src="https://cloud.githubusercontent.com/assets/2346707/16156512/f7e96946-34f7-11e6-972f-88b8eff19323.jpg" width="600" />

This wouldn't be so confusing if there were actually reflective surfaces behind me...

I won't be sleeping tonight.

**Comment by Alhadis** [comment]
Wait, sorry... I realised what the white specks were... they were just the (extremely dull) sheen of metallic bolts under my shelf. Makes sense now.

Also, my hair looks fucking FABULOUS. New display pic.

**Comment by jacobrosenthal** [comment]
In a perfect world this would have been some slenderman shit that went on
for weeks. Shame on you for solving it so quick :)

**Comment by Qix-** [comment]
Sorry to gravedig but `-w 2` did indeed solve this for me as well.

Perhaps it should be the default?

**Comment by rharder** [comment]
v0.2.14 (finally) makes a wait of 3 seconds the default.
