### ISSUE TITLE
Does not work on Yosemite

### ISSUE THREAD

**Issue by beny** [rharder/imagesnap#8]
Simply calling `imagesnap` returns error

```
$ imagesnap 
    Could not create capture session.
Error.
Capturing image from device "FaceTime HD Camera (Built-in)"...
```

**Comment by Noreaster76** [comment]
I don't experience this same behavior. In addition, with the code included in https://github.com/rharder/imagesnap/pull/13, I have it running successfully in OS X El Capitan. Are you still experiencing this issue?

**Comment by michaelwschultz** [comment]
No issues here. Think this issue should be closed.

**Comment by sshaw** [comment]
I noticed something similar when connecting my laptop to a monitor. Running `imagesnap -l` did not show any devices. Once I started and stopped FaceTime, it showed `"FaceTime HD Camera (Built-in)"`.

**Comment by carleryd** [comment]
I had this same issue on El Capitan MBA 2012.
Running this command solved the problem without any restart:
```sudo killall VDCAssistant```

**Comment by maedoc** [comment]
I ran into 
```
2018-04-10 12:47:34.987609+0200 imagesnap[31620:6736480] [General] *** -[AVCaptureStillImageOutput captureStillImageAsynchronouslyFromConnection:completionHandler:] Inactive/invalid connection passed
```
and @carleryd's command solved the problem
